"""Add Port Mapping

Revision ID: ba52e4725227
Revises: 0653dc97382a
Create Date: 2025-09-26 14:07:07.307079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ba52e4725227'
down_revision: Union[str, None] = '0653dc97382a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portmapping',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('miner_hotkey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_id', sa.Uuid(), nullable=False),
    sa.Column('internal_port', sa.Integer(), nullable=False),
    sa.Column('external_port', sa.Integer(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('verification_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_executor_success_time', 'portmapping', ['executor_id', 'is_successful', 'verification_time'], unique=False)
    op.create_index(op.f('ix_portmapping_executor_id'), 'portmapping', ['executor_id'], unique=False)
    op.create_index(op.f('ix_portmapping_miner_hotkey'), 'portmapping', ['miner_hotkey'], unique=False)
    op.create_index(op.f('ix_portmapping_verification_time'), 'portmapping', ['verification_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portmapping_verification_time'), table_name='portmapping')
    op.drop_index(op.f('ix_portmapping_miner_hotkey'), table_name='portmapping')
    op.drop_index(op.f('ix_portmapping_executor_id'), table_name='portmapping')
    op.drop_index('idx_executor_success_time', table_name='portmapping')
    op.drop_table('portmapping')
    # ### end Alembic commands ###
