"""add price_per_hour into Executor model

Revision ID: 20ad305cfb00
Revises: eb0b92cbc38e
Create Date: 2025-09-02 10:23:49.421050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '20ad305cfb00'
down_revision: Union[str, None] = 'eb0b92cbc38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor', sa.Column('price_per_hour', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executor', 'price_per_hour')
    # ### end Alembic commands ###
